"""
Write the structured synthetic dataset to disk for manual CLI runs.

Usage::

    python scripts/make_synthetic_data.py [OUTPUT_DIR]

Defaults to ``.plans/data`` (gitignored). Writes the alignment as
FASTA, NEXUS and PHYLIP, a metadata CSV and a README describing what
is in it. The automated CLI tests build the same dataset in a temp
directory, so this is only for poking at the tools by hand.
"""

import csv
from pathlib import Path
import sys

from pypopart.io.fasta import FastaWriter
from pypopart.io.nexus import NexusWriter
from pypopart.io.phylip import PhylipWriter
from pypopart.io.synthetic import (
    LONG_BRANCH_STEPS,
    POPULATIONS,
    SAMPLES_PER_POPULATION,
    simulate_structured_alignment,
)

README = """# Synthetic structured dataset

Generated by `scripts/make_synthetic_data.py` from
`pypopart.io.synthetic.simulate_structured_alignment` (seed 7, 300 bp).
Regenerate rather than edit.

{n_seqs} sequences, {n_haps} distinct haplotypes, {n_pops} populations
({pops}), {per_pop} samples each plus a few duplicated private haplotypes.

What is in it, and what it exercises:

- Each population has its own founder 2-4 steps off a shared ancestor,
  a sub-founder 1-2 steps further on, six samples on the founder, four
  on the sub-founder and ten with private mutations. Nested clades, node
  frequencies, chains as well as stars.
- `Island` shares the `Coastal` founder for three samples: a mixed
  population node, drawn as a pie.
- `Desert` has three haplotypes two steps apart pairwise with their
  common neighbour unsampled: MJN and TSW add median vectors.
- `Alpine` is {long} mutations from the ancestor and one `Island` sample
  is {long} from its founder: edges past the tick threshold show a
  numeral instead of a comb.
- Three `Riverine` samples carry a two-base gap, one `Highland` sample
  an `N`.

Files: `synthetic.fasta`, `synthetic.nex`, `synthetic.phy` (same data),
`synthetic_metadata.csv` (`id,population`).

Smoke run:

    pypopart load synthetic.fasta -m synthetic_metadata.csv
    pypopart network synthetic.nex -a mjn -o synthetic_mjn.graphml
    pypopart analyze synthetic_mjn.graphml --stats --topology --popgen -a synthetic.fasta
    pypopart visualize synthetic_mjn.graphml -o synthetic.png
"""


def main(argv: list) -> int:
    """
    Write the dataset.

    Parameters
    ----------
    argv : list
        Command-line arguments after the script name; the first, if
        given, is the output directory.

    Returns
    -------
    int
        Process exit code.
    """
    out = Path(argv[0]) if argv else Path('.plans/data')
    out.mkdir(parents=True, exist_ok=True)

    alignment, populations = simulate_structured_alignment()

    FastaWriter(out / 'synthetic.fasta').write_alignment(alignment)
    NexusWriter(out / 'synthetic.nex').write_alignment(alignment)
    PhylipWriter(out / 'synthetic.phy').write_alignment(alignment)

    with open(out / 'synthetic_metadata.csv', 'w', newline='') as handle:
        writer = csv.writer(handle)
        writer.writerow(['id', 'population'])
        for sample_id, population in populations.items():
            writer.writerow([sample_id, population])

    (out / 'README.md').write_text(
        README.format(
            n_seqs=len(alignment),
            n_haps=len({s.data for s in alignment}),
            n_pops=len(POPULATIONS),
            pops=', '.join(POPULATIONS),
            per_pop=SAMPLES_PER_POPULATION,
            long=LONG_BRANCH_STEPS,
        )
    )
    print(f'Wrote {len(alignment)} sequences to {out}/')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
